### ISSUE TITLE
Enhance Security-Part on Documentation

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad-admin-documentation#10]
Currently our Security-Part of our Admin-Documentation is poorly written.
Actually it lacks the needed information which causes Problems with clean integration of this.

( See: https://github.com/zammad/zammad/issues/2349 )

I'll add a write up for Google+ to fix that issue

**Comment by ndom91** [comment]
Ahh it uses the google+ api? This might get shutdown with google+ soon. I recommend switching to normal Google api oauth2 authentication

**Comment by MrGeneration** [comment]
Thanks for the hint, yes I thought that it would get troublesome and will discuss this in our Team.

**Comment by thorsteneckel** [comment]
JFI: We're using the `omniauth-google-oauth2` gem which [states in it's documentation](https://github.com/zquestz/omniauth-google-oauth2#google-api-setup) that these are required and refers to the [Google documentation](https://github.com/zquestz/omniauth-google-oauth2#omniauth-google-oauth2-strategy).

**Comment by ndom91** [comment]
Ah okay. I just recently built a php web app my team at work and we use G Suite, so I integrated Google Auth, but never had to enable the google+ api. Maybe it's using something else in the background?

**Comment by MrGeneration** [comment]
Google documentation part has been updated to the most current state.
