### ISSUE TITLE
o365-E-mail-channel needs admin consent to be disabled

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad-admin-documentation#130]
Admin consent needs to be disabled in the App-configuration of the o365-Cloud. Screenshots are available in Zammad-ticket #10101086.

_Could not add labels, so sorry for unlabeled issue._

**Comment by MrGeneration** [comment]
This will be addressed by d71d900d0a72cac6bc022c6f49cb76ae088f70f0
