### ISSUE TITLE
Rewrite Office365 Login-App (Security)

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad-admin-documentation#21]
The third-party application for Office 365 needs to be updated, as Microsoft changed things again.
The new portal is now `https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade` which requires us to recheck the process and also update screens.

**Comment by terdinatore** [comment]
What is the status of this enhancement?

**Comment by MrGeneration** [comment]
The status is still to do.
