### ISSUE TITLE
Add new operators for input fields

### ISSUE THREAD

**Issue by fliebe92** [zammad/zammad-admin-documentation#252]
We need to update the admin documentation to include the new operators for https://github.com/zammad/zammad/issues/4661.

It might be required to update screenshots and add good explanations for `is`, `is not`, `starts with`, and `ends with` for triggers, overviews, postmaster filters, ...

**Comment by ralf401** [comment]
Hi @fliebe92,

this is already done. The operators are listed [here](https://admin-docs.zammad.org/en/pre-release/misc/object-conditions/basics.html) under Text field (input) as well as in Email > Filters. In the trigger and overview section, there are references to the object conditions. 

Feel free to double check and let me know, if the existing (pre-release) docs are sufficient or if I should add more stuff.

**Comment by fliebe92** [comment]
Hi @ralf401. Should be fine then :)
