### ISSUE TITLE
Enhancement - Channel E-Mail and shared office365 mailboxes

### ISSUE THREAD

**Issue by dhemeier** [zammad/zammad-admin-documentation#26]
Hey all,

the documentation (https://admin-docs.zammad.org/en/latest/channels-email.html) describes that the usage of shared mailboxes is not supported by Zammad, this is not correct. For my own implementation, I use exactly this function.

Small guide:
- Open Office365 Admin Center
- Select the "shared mailbox" user (which has no licenses assigned)
- Go to "reset password" and set a new password (don't use "need update on first login")

- In Zammad add the e-mail address with the following settings:
Type: IMAP
Host: outlook.office365.com
User: Shared e-mail
Password: set as above explained
SSL/TLS: yes
Port: 993

Hint: With the password you can also add the e-mail in other applications as normal IMAP mailbox.

Greetings
Dennis

**Comment by MrGeneration** [comment]
By now Microsoft is going to disable basic authentication which is why this issues suggested behavior will be a dead end soon.

However, the basic information is technically not incorrect which is why we're going to introduce a tip tooltip that hints for it with e904fa837824467c00e513cad0c22116bf08e02f

**Comment by FabianTe** [comment]
Hi @MrGeneration, sorry for abusing this issue. I must migrate to a shared mailbox model and will also not be able to use Basic. The OAuth based integration works nice with a simple user but I have not yet been able to configure it it such a way that I authenticate with some user that has access to a mailbox and then fetch mails from that mailbox via that user.

Is this even possible right now?

**Comment by MrGeneration** [comment]
We're not answering technical questions on our repos but our community: https://community.zammad.org

If you're a paying customer use the to you known communication channels.
