### ISSUE TITLE
Monitoring documentation outdated

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad-admin-documentation#261]
The documentation still mentions a token returned by the monitoring endpoint - that was removed with Zammad 6.0.
It may also make sense to mention that, while "unprocessible mail" are being noted, "oversized mail" are not.

**Comment by ralf401** [comment]
Tried it and still got the token returned. So I will leave it as is, I just add the note for the oversized mail.

**Comment by mgruner** [comment]
@ralf401 the token will only be returned if you have `admin.monitoring` permissions. That should not be the case for monitoring users, I hope. Please check that again.

**Comment by mgruner** [comment]
Yes, the token should not be returned if you do not have `admin.monitoring` permissions, but only request via token, not via session cookie.
