### ISSUE TITLE
PGP: Describe the configuration of the PGP integration

### ISSUE THREAD

**Issue by dvuckovic** [zammad/zammad-admin-documentation#264]
For inspiration, see [the existing S/MIME section](https://admin-docs.zammad.org/en/latest/system/integrations/smime/index.html).

The cookbook from the developer manual can be provided as a base document.

```[tasklist]
### Tasks
- [x] Add a section for PGP under `system/integrations`
```

**Comment by dominikklein** [comment]
@ralf401 can be closed or?
