### ISSUE TITLE
Documentation of Gitlab OAuth not accurate

### ISSUE THREAD

**Issue by Ruesa18** [zammad/zammad-admin-documentation#276]
[The documentation](https://admin-docs.zammad.org/en/latest/settings/security/third-party/gitlab.html) states that the url should be provided as `https://{git_host}/api/v4/` when instead only `https://{git_host}/` is required. If the full url is given, the application won't work as intended.

To do:
- change the description to say `https://{git_host}/` instead of `https://{git_host}/api/v4/`
- update the screenshot

**Comment by ralf401** [comment]
See issue https://github.com/zammad/zammad-admin-documentation/issues/240

Will be fixed there.
