### ISSUE TITLE
Missing information about Redis

### ISSUE THREAD

**Issue by slalabs** [zammad/zammad-admin-documentation#303]
Zammad 6 requires Redis, but only on [this page](https://docs.zammad.org/en/latest/appendix/configure-env-vars.html) is a small sentence about it. The Debian Redis package, for example, is not working out of the box with Zammad. Please provide better documentation.

**Comment by ralf401** [comment]
Hi @slalabs, thanks for your suggestion. We included it already [here](https://docs.zammad.org/en/latest/prerequisites/software.html) under 2.7, so I close your issue.
