### ISSUE TITLE
elasticsearch SSL verify

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad-admin-documentation#312]
New hidden elastic search setting to define ssl_verify for elasticsearch.

https://docs.zammad.org/en/latest/install/elasticsearch.html

https://github.com/zammad/zammad/commit/449704771c806239cb5e620d6fe81c23695d150d

**Comment by ralf401** [comment]
Issue in wrong repo, manual linking PR: https://github.com/zammad/zammad-documentation/pull/348

**Comment by ralf401** [comment]
See https://github.com/zammad/zammad-documentation/pull/348
