### ISSUE TITLE
reporting screenshot exchange

### ISSUE THREAD

**Issue by KoJie** [zammad/zammad-admin-documentation#32]
images/manage/Zammad_Helpdesk_-_Report_Profile2.jpg

The screenshot of the reporting shows the numbers of the graph within the graph and not, as intended, on the ordinate axis. Would be nice to show a "correct" screenshot.

**Comment by MrGeneration** [comment]
This issue will be addressed with the above PR as soon as you approved it.

**Comment by MrGeneration** [comment]
This has been solved by now.
