### ISSUE TITLE
Language selection currently is missing completely on latest

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad-admin-documentation#346]
![image](https://github.com/zammad/zammad-admin-documentation/assets/6549061/34a4193d-2b82-4da1-8058-b214d73e5356)

**Comment by dvuckovic** [comment]
This is intentional, no language translation is currently above 50% complete, and we decided to activate them in the future only above 80% completeness rate. There is work ongoing internally in pushing German + Serbian above this threshold. Stay tuned!
