### ISSUE TITLE
Reword the whole chapter on objects so it refers to attributes appropriately

### ISSUE THREAD

**Issue by dvuckovic** [zammad/zammad-admin-documentation#361]
* **Object**
  A business object in Zammad (i.e. Ticket, User, Group...)

* **Object Attribute**
  A custom field for an **object** in Zammad (i.e. Text, Boolean, Integer...)

Currently, the whole [Objects chapter](https://admin-docs.zammad.org/en/latest/system/objects.html) refers to both entities as _objects_, which is very confusing.

Consider separating the two terms, and being more specific when talking about **object attribute types** and configuration of **object attributes**. Basically, the only change that can be made to an **object** is which type of **object attributes** are defined. The actual entity that most of the chapter is trying to explain are **object attributes**, not **objects**.

However, it's perfectly fine to refer them as _attributes_ in a short form, so we can avoid too long sintagmi.

**Comment by MrGeneration** [comment]
The section heavily uses "object" as wording, as the menu point also has this name in the UI. Maybe that needs a rewording as well.

**Comment by dvuckovic** [comment]
Yes, menu / top level section title actually makes sense, as it's in line with the UI. I'm just having trouble in understanding the rest of the text since it always refers to _objects_ :)

**Comment by ralf401** [comment]
@dvuckovic I would have a look at it, if ok?
