### ISSUE TITLE
Add something about translation of attributes

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad-admin-documentation#384]
It is possible to translate attributes in trigger (and maybe text modules) with the following syntax:
`#{t(ticket.state.name)}`

This is not mentioned in the documentation yet and needs to be added.

**Comment by ralf401** [comment]
@YetAnotherGerrit can you explain what you mean or give an example? For the general translatability, we have a note in the [admin-docs](https://admin-docs.zammad.org/en/latest/system/objects/types.html).
But you probably mean another feature, right?

**Comment by YetAnotherGerrit** [comment]
When you phrase texts in text modules, trigger, scheduler, signatures you can use `#{name}` to include values of different attributes within. These can be translated using `#{t(name)}`. This is currently not mentioned in the documentation.

**Comment by dominikklein** [comment]
But is it really for all situations? I'm not sure about the stuff which is replaced inside the frontend (e.g. text modules or signature).

**Comment by ralf401** [comment]
I tried it in text modules, trigger and scheduler. I wrote that it works in these 3 areas.

**Comment by ralf401** [comment]
Tested it again => just working in trigger and scheduler. 

Pushed changes again to PR.
