### ISSUE TITLE
Add channel SMS

### ISSUE THREAD

**Issue by KoJie** [zammad/zammad-admin-documentation#40]
General documentation for the integration of the channel "SMS"
```[tasklist]
### Tasks
- [x] Creating documentation
- [ ] Creating translation
```

**Comment by ralf401** [comment]
Creating documentation -> review -> merge -> creating translation -> done

**Comment by dominikklein** [comment]
@dvuckovic Maybe you can take over the review here?

**Comment by ralf401** [comment]
Translation can be made in the future, if required (open question with PO and marketing)

=> done
