### ISSUE TITLE
Sendmail adapter: Please explain how to setup msmtp with multiple accounts

### ISSUE THREAD

**Issue by ri0t** [zammad/zammad-admin-documentation#42]
In general i'd like to be able to specify how sendmail (i.e. msmtp) gets called, we need e.g. this command line:
`msmtp -t --read-envelope-from -a supportmailaccount`
where `supportmailaccount` is a defined account in /etc/msmtprc. Perhaps msmtp could guess this via the --read-envelope-from, but i can't even get that configured currently.

Thank you in advance!

**Comment by MrGeneration** [comment]
Sorry but this sounds rather like a technical question?
If so, please ask your technical question at the community: https://community.zammad.org

However, please note that Zammad supports SMTP and sendmail only.
I have no expertise on how different msmtp is, but we can't provide any useful help here.

**Comment by ri0t** [comment]
msmtp (or specifically msmtp-mta) is a sendmail replacement that can be configured to use smtp accounts for transmitting mail. It is usually used in situations where the sending application has sendmail and smtp support, but smtp support has e.g. problems with self signed certificates.

**Comment by MrGeneration** [comment]
Closing as sendmail and their alternatives are out of scope of Zammad documentation. 
If the alternatives behave exactly like sendmail, the application should work without issues.
