### ISSUE TITLE
update of the organisation-import

### ISSUE THREAD

**Issue by KoJie** [zammad/zammad-admin-documentation#43]
zammad-admin-documentation/manage/users.rst

A more detailed explanation of the User Organization Import should be added. To clarify questions like these:

- Do organizations have to be imported in the first step, so that users can be assigned to the organization via user import in the second step?  Or is the organization automatically stored when importing the users with assigned organization

- After the initial user import, can I perform another import to update the data?

**Comment by MrGeneration** [comment]
This is already handled:

* ![image](https://user-images.githubusercontent.com/6549061/173197347-15c9103c-0c26-4d1c-aa27-f599879800ab.png)
* ![image](https://user-images.githubusercontent.com/6549061/173197368-393ea200-566d-417c-9e79-98f65b5a795d.png)
