### ISSUE TITLE
Add name of env-variable to S3 documentation

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad-admin-documentation#433]
The documentation of the S3 storage mentions that the URL can be set by an env variable, too. But not the name of the env-variable:
https://admin-docs.zammad.org/en/latest/settings/system/storage.html

I could also not find the variable here:
https://docs.zammad.org/en/latest/appendix/configure-env-vars.html

**Comment by tschaefer** [comment]
@YetAnotherGerrit This was a willful decision not to document the usage of the environment variable in detail. By following the described steps into the rabbit hole, you'll find further information.

![2023-12-13-130824_533x83_scrot](https://github.com/zammad/zammad-admin-documentation/assets/708717/6036acf2-512d-478d-aa42-fdf75f91a206)

```
$ cat config/zammad/storage.yml.dist
...
# The above configuration may also be provided in a URL-like format in this
# configuration file or as an environment variable named S3_URL.
# If the url is provided in the configuration file the environment variable is
# ignored.
s3:
  url: 'https://key:secret@s3.eu-central-1.amazonaws.com/zammad-storage-bucket?region=eu-central-1&force_path_style=true'
```

**Comment by mgruner** [comment]
We will have to document it at least when adding S3 to the containerized deployments.
