### ISSUE TITLE
Add documentation on Resetting users Two Factor Authentication

### ISSUE THREAD

**Issue by slinkytoad** [zammad/zammad-admin-documentation#441]
Would it be possible to have documentation added to show how to reset a users Two-Factor Auth? I was able to find reference to the method in the feature's initial issue [#4595](https://github.com/zammad/zammad/issues/4595) but nothing in the Admin [docs](https://github.com/zammad/zammad-admin-documentation/blob/main/settings/security/two-factor.rst).

**Comment by ralf401** [comment]
Hi @slinkytoad, thanks for your suggestion. I will add some information about that.
