### ISSUE TITLE
Wrong German translation "Admnin > Roles > Admin permission > Verwalten > Textbausteine"

### ISSUE THREAD

**Issue by Bozo0511** [zammad/zammad-admin-documentation#491]
There is a wrong name in the German Translation of the Documentation:
https://admin-docs.zammad.org/de/latest/manage/roles/admin-permissions.html

The "Verwalten > Textbausteine" needs to be changed to "Verwalten > Vorlagen"
![2024-03-11 12_47_51-Admin-Berechtigungen — Zammad Admin Documentation Dokumentation – Opera](https://github.com/zammad/zammad-admin-documentation/assets/94919964/c144d726-769b-4d31-a2be-d405ed8fdd22)

**Comment by MrGeneration** [comment]
The translation is handled at https://translations.zammad.org so this is not really a documentation issue.
