### ISSUE TITLE
Clicking "Next" goes to "Branding" on WhatsApp-Prepration-Site

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad-admin-documentation#524]
Version: pre-release

When clicking the "Next"-Button on the [WhatsApp-Prepration-Site](https://admin-docs.zammad.org/en/pre-release/channels/whatsapp/preparation.html), it jumps to "Branding".

**Comment by ralf401** [comment]
Thanks for reporting! @dvuckovic checked it and found out that there is nothing we can do now, unfortunately. This is probably a bug in Sphinx and we can't  solve it on our own. I also tried to change the structure of the WhatsApp documentation, but it didn't work too.

I guess these "Previous" and "Next" buttons aren't used by many readers and I close this issue for now. In the new documentation system we have the possibility to manually define/override which page is the previous/next.

**Comment by dvuckovic** [comment]
OK, on second look, it's not a Sphinx bug but an inconsistent content structure of our docs page. We have a solution, it will (hopefully) be merged soon.
