### ISSUE TITLE
Complement trigger notifications to all agents

### ISSUE THREAD

**Issue by Vogelkoje** [zammad/zammad-admin-documentation#54]
Add at https://admin-docs.zammad.org/en/latest/manage/trigger.html#conditions
an information with trigger notifications, if selected action > e-mail > "all agents"

With such a setting, the notification is sent to all agents with full authorization. However, only to agents who are in the group to which the ticket is assigned and who only have full authorization in this group.

**Comment by MrGeneration** [comment]
Do you mean this page?
https://admin-docs.zammad.org/en/latest/manage/trigger/how-do-they-work.html
