### ISSUE TITLE
Link to Twitter/X Note broken in German version

### ISSUE THREAD

**Issue by itkfm** [zammad/zammad-admin-documentation#653]
The link in the infobox on the Twitter/X page is broken for the German version.
No link is generated – just a `<span>` tag.

As far as I can tell, this means that the *Twitter/X note* page is only accessible through search for the German admin docs.

<details>
<summary>Screenshot</summary>

![image](https://github.com/user-attachments/assets/332afd09-6e41-4231-a36e-1fb68fb469c6)

![image](https://github.com/user-attachments/assets/334e5afa-d7da-4b54-88ec-ed3680797208)

</details>

**Comment by MrGeneration** [comment]
Translations are handled in weblate:
https://translations.zammad.org/projects/documentations/admin-documentation-latest/de/

Please feel very welcome to adjust this, you can use your GitHub account to do so.
