### ISSUE TITLE
Hint for catchalls and "sending mails to yourself" went over board during transition

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad-admin-documentation#68]
During rewriting Zammads email documentation it seems we kicked out the quite crucial hint that Zammad has to know all of it's aliases, as other wise you'll write to Zammad which does stuff you don't expect.

https://admin-docs.zammad.org/en/latest/channels/email/index.html

**Comment by ralf401** [comment]
I think it's still present -> https://admin-docs.zammad.org/en/latest/channels/email/accounts/secondary-addresses.html
