### ISSUE TITLE
Extended information about the triggers

### ISSUE THREAD

**Issue by Vogelkoje** [zammad/zammad-admin-documentation#75]
https://admin-docs.zammad.org/en/latest/manage/trigger.html
https://admin-docs.zammad.org/en/latest/manage/trigger/how-do-they-work.html

More information may be required in the documentation. How is the exhaust air of the triggers concrete. Is stopped at a matching hit or are all triggers processed. How about alphabetical order. If the conditions are identical, all triggers with this condition or only alphabetically.

**Comment by MrGeneration** [comment]
During the QA of the documentation this were essential parts that were removed.
So it's unlikely we'll add them again. While I partly agree, this is currently nothing I will provide.


If this comes from a Ticket, please also provide a reference for better understandings within the Team.
