### ISSUE TITLE
Rework link template documentation

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad-admin-documentation#78]
https://github.com/zammad/zammad/issues/3214#issuecomment-709360853

Maybe we could improve the documentation with the 2 use cases someday.

https://github.com/zammad/zammad-admin-documentation/blob/master/system/objects.rst

**Comment by MrGeneration** [comment]
Holy moly thats a tons of notifications shipping here.
I got a rework todo marked for objects already.

**Comment by rolfschmidt** [comment]
Drink a beer and enjoy your vacation 🍹  Sorry for the notifications...
