### ISSUE TITLE
Wrong URL in Zammad for Microsoft 365 channel docs

### ISSUE THREAD

**Issue by benmo** [zammad/zammad-admin-documentation#84]
The documentation link in Zammad leads to `https://admin-docs.zammad.org/en/latest/channels/microsoft365.html`, but that results in a 404 since the correct URL is `https://admin-docs.zammad.org/en/latest/channels/microsoft365/index.html`.

![image](https://user-images.githubusercontent.com/69507095/99584896-ddc72e80-29e5-11eb-8c53-f46c4d4e2a98.png)

Is it possible to set up a redirection? That would probably be the easiest solution.

**Comment by MrGeneration** [comment]
Doh forgot about adjusting the links sorry.
Will do tomorrow.

**Comment by MrGeneration** [comment]
Thanks for the report.
I internally already provided a MR to solve the link issue in general.

For now the documentation automatically redirects to the correct URL.
