### ISSUE TITLE
Email Notification (self hosted), edit does not work

### ISSUE THREAD

**Issue by peduso** [zammad/zammad-admin-documentation#85]
Hi, 
I got an error when setting up the system. Sendmail does not work. Now when I try to change sendmail to smtp I get the same error (I think).

554 5.2.0 STOREDRV.Submission.Exception:SendAsDeniedException.MapiExceptionSendAsDenied; Failed to process message due to a permanent exception with message Cannot submit message. 0.35250:0A002085, 1.36674:0A000000, 1.61250:00000000, 1.45378:02000000, 1.44866:5E200000, 1.36674:0E000000, 1.61250:00000000, 1.45378:63200000, 1.44866:3A010000, 16.55847:0C100000, 17.43559:0000000024020000000000000000000000000000, 20.52176:140F1B8E1900103100000000, 20.50032:140F1B8E8917000000000000, 0.35180:140F1B8E, 255.23226:0A00D588, 255.27962:0A000000, 255.27962:0E000000, 255.31418:0A00E788, 0.35250:1F001432, 1.36674:0A000000, 1.61250:00000000, 1.45378:02000000, 1.44866:38000000, 1.36674:32000000, 1.61250:00000000, 1.45378:3D000000, 1.44866:01000000, 16.55847:A4000000, 17.43559:0000000070030000000000000100000000000000, 20.52176:140F1B8E1900101053000000, 20.50032:140F1B8E891700001B230000, 0.35180:58000000, 255.23226:4800D13D, 255.27962:0A000000, 255.27962:32000000, 255.17082:DC040000, 0.27745:25230000, 4.21921:DC040000, 255.27962:FA000000, 255.1494:2A230000, 0.38698:05000780, 0.37692:01000000, 0.37948:0F010480, 5.33852:00000000534D545000010480, 7.36354:01000000000001091A010480, 4.56248:DC040000, 7.40748:010000000000010B1A010480, 7.57132:000000000000000000000000, 1.63016:32000000, 4.39640:DC040000, 8.45434:666AB5283596CE48ACB43B4D29AE6B282CF31618, 5.10786:0000000031352E32302E333631312E3032353A5649315052303430324D42333832333A36303931393164382D373236352D346231332D623836342D3638303435663766653437620000000000, 7.51330:4EE6F828C494D80818000000, 0.39570:00000000, 1.55954:0A000000, 0.49266:02000000, 1.33010:0A000000, 2.54258:00000000, 0.40002:7A000000, 1.56562:00000000, 1.64146:32000000, 1.33010:32000000, 2.54258:DC040000, 255.1750:AF000000, 255.31418:0A005D36, 0.22753:28250000, 255.21817:DC040000, 0.64418:0A00F565, 4.39842:DC040000, 0.41586:B9000000, 4.60547:DC040000, 0.21966:8A250000, 4.30158:DC040000 [Hostname=VI1PR0402MB3823.eurprd04.prod.outlook.com] 

I have put in the same login information I use with the E-Mail Account. There it works perfect. 

If anyone has an Idea it would be wonderful

Zammad 3.6.x
Ubuntu 20.x

peduso

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
