### ISSUE TITLE
Tickets that can be found in the activity-stream

### ISSUE THREAD

**Issue by KoJie** [zammad/zammad-admin-documentation#87]
zammad-admin-documentation/manage/groups/access-levels.rst

There is no information regarding group authorisation, which is often requested:
Which tickets can be seen in the activity stream in the dashboard? 
--> You need at least "read" permission for this.

Please include this in a suitable place. Thank you

**Comment by MrGeneration** [comment]
I believe this is already covered by group access levels

![image](https://user-images.githubusercontent.com/6549061/169464481-0a016e64-9708-42b5-8a68-274d7722ffe9.png)


https://admin-docs.zammad.org/en/latest/manage/groups/access-levels.html
