### ISSUE TITLE
add. note: DSGVO/ deleting tickets <> Reporting

### ISSUE THREAD

**Issue by KoJie** [zammad/zammad-admin-documentation#88]
zammad-admin-documentation/system/data-privacy.rst

It is often asked how the reporting behaves when tickets are deleted. Therefore, it should be added either in the body text or in the FAQ's that deleted tickets are also deleted for reporting. 
As a recommendation, so that these tickets still show up in the statistics, automation can help to set the customer to a "dummy customer".

**Comment by MrGeneration** [comment]
Sorry I thought it would be common sense that if you remove ticket data this also affects reporting.
We'll see on how we can merge that into the docs.

**Comment by KoJie** [comment]
you are right but it makes it more obvious. Statistics are often forgotten. This clearly mentions this point again, so that you can also look at this function from a different angle and think this through.
