### ISSUE TITLE
Add definition of "knowledge_base.reader" permission

### ISSUE THREAD

**Issue by KoJie** [zammad/zammad-admin-documentation#89]
- The definition of the permission "knowledge_base.reader" is missing.
 that might fit here best: https://admin-docs.zammad.org/en/latest/manage/roles/index.html

- And the information that customer can always see "Public" articles - that might better fit here: https://admin-docs.zammad.org/en/latest/manage/knowledge-base.html

--> That causes misunderstandings between the right to see KB-articles as a customer vs. an agent.

**Comment by MrGeneration** [comment]
> The definition of the permission "knowledge_base.reader" is missing.
that might fit here best: https://admin-docs.zammad.org/en/latest/manage/roles/index.html

It's not, you can find it right below "agent permissions"
https://admin-docs.zammad.org/en/latest/manage/roles/agent-permissions.html


> And the information that customer can always see "Public" articles - that might better fit here: https://admin-docs.zammad.org/en/latest/manage/knowledge-base.html

We strictly divide our documentations in between administration and usage.
This is why you can find the above mentioned hint on the bottom of the user documentations page. The admin documentation does hint for this documentation page (that it may contain further relevant information)
https://user-docs.zammad.org/en/latest/extras/knowledge-base.html


---

I'm sorry, but I don't see why we should provide more duplicate information that is already available.
This is why I'll be closing this issue.

**Comment by KoJie** [comment]
alright, the first one is very hidden - but okay.

But I disagree with the second part. Because as an Admin I don't want to switch to the User-Doc! I want to find all relevant information about the settings in the admin-documentation.

**Comment by KoJie** [comment]
*Proposal*

you could also solve it as follows: instead of

knowledge_base.reader: read privileges for internal & public content

we can write:

knowledge_base.reader: read privileges for internal content

(because you do not give the right to read "public KB article" with this hook- That makes it more definite.

**Comment by MrGeneration** [comment]
How about this then?

![image](https://user-images.githubusercontent.com/6549061/105162472-f30a2780-5b12-11eb-972a-8c5c30b99055.png)

**Comment by KoJie** [comment]
I like the Hint-option.
But it would be more unambiguous to write: Public articles are always visible to every user.

**Comment by MrGeneration** [comment]
We try to keep the number of words as low as possible.
I believe that in context, there's no different in between `public articles are always visible` and `public articles are always visible to every user`

**Comment by MrGeneration** [comment]
I asked other persons as well that stated that version 2 with "[...] every user" may be misunderstood in terms of "you need an account" which is not true.
I'm therefor going to apply my suggestion.
