### ISSUE TITLE
English texts in screenshot

### ISSUE THREAD

**Issue by thorsteneckel** [zammad/zammad-admin-documentation#9]
There is [a screenshot](https://zammad-admin-documentation.readthedocs.io/en/latest/_images/permission-examples2.jpg) in the following documentation page which contains text:
https://zammad-admin-documentation.readthedocs.io/en/latest/manage-roles.html#agent

There should be no texts inside of screenshots.

**Comment by MrGeneration** [comment]
I fixed this last week and did some additional changes. :) 

See: https://github.com/zammad/zammad-admin-documentation/commit/a54be72c77cf2d055e0a6cfe63c38ba7db9bf03a
